### ISSUE TITLE
ArgumentError when trying to seed the database

### ISSUE THREAD

**Issue by leesharma** [rubyforgood/habitat_humanity#96]
This issue comes from #94 (Problem 3)

**System:** Fedora 23

### Current Behavior

Trying to seed the database blows up with an ArgumentError:

```bash
ArgumentError: Factory not registered: work_site
  ~/.rvm/gems/ruby-2.3.1/gems/factory_girl-4.7.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
  ~/src/h4h/db/seeds.rb:5:in `block in <top (required)>'
  ...
  ~/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  ~/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  -e:1:in `<main>'
  Tasks: TOP => db:setup => db:seed
  ...
  == Restarting application server ==
  touch: cannot touch 'tmp/restart.txt': No such file or directory
```

#### Steps to Reproduce

```bash
rake db:seed
```

### Desired Behavior

`rake db:seed` should successfully seed the database

#### Proposed Solution

require 'factory_girl_rails' rather than 'factory_girl' in db/seeds.rb.

**Comment by glroman** [comment]
I'll try fixing this.
